### ISSUE TITLE
Green horizontal scrollbar in Solarized Light

### ISSUE THREAD

**Issue by cabello** [4lex4/intellij-platform-solarized#14]
Hi 👋 ,

Thanks for making and maintaining this Solarized theme, I've been using Solarized on my editors for the past few years and I appreciate the community support.

I personally always use Solarized Light, and I noticed a small thing with this theme on PyCharm.

While the vertical scrollbar looks sane, the horizontal scrollbar is green:

<img width="1171" alt="Screen Shot 2020-04-24 at 9 59 07 AM" src="https://user-images.githubusercontent.com/60936/80221377-316dc700-8613-11ea-9c19-542d095b85ce.png">

For a moment I thought it was an error, mark of that file but I opened other files and they all showed the same color, I also switch to Solarized Dark which does not display the issue.

I see a discrepancy in how many `ScrollBar.*` options are set for each theme, Dark has 24 while Light has 16, could that indicate a possible fix?

Another thing I noticed is that ScrollBar options are the only one in the theme that have 8 alphanumeric strings (`value="[a-z0-9]{8}"` regex) when compared to other options that look like RGB hexdex colors.

Thank you again for sharing this theme.
Let me know if I can help with testing or even making a PR (I tried tweaking the options a bit without much success, I have very little context on JetBrains theming).

**Comment by 4lex4** [comment]
Clean up `<product><version>/colors` folder, i. e. remove all the __`\*Solarized\*Light/Dark\*.(xml/icls)`__ files from that. (See the location of directories used by IDE to store settings for your OS [here](https://intellij-support.jetbrains.com/hc/en-us/articles/206544519-Directories-used-by-the-IDE-to-store-settings-caches-plugins-and-logs)).

That's a bug in IntelliJ IDEA, that occurs **after editing** the theme in the IDE. Opacity is used to set some ScrollBar values in this project (as well as in the bundled IntelliJ Light and Darcula themes), i. e. 32 bit values, but by some reason IDEA after editing changes that to 24 bit value, ignoring the 1st and the last hex digits, so that's why you get green.

But you can still customize the theme in the IDE: after editing copy ScrollBar.* values from original xml theme and paste those into *Solarized*Light/Dark*.icls replacing.

**Comment by cabello** [comment]
You are on the money! I should've said that I edited some of the theme, I prefer the default text to be a bit darker instead of the light grey.

I followed your instructions and no more green bar. Huzzah 🎉 

Thank you for your assistance 🙇
